python ViCo/env.py --head_less \
--output_dir output/odm \
--multi_process \
--skip_avatar_animation \
--scene NY \
--outdoor_objects_max_num 2 \
--resolution 512 \
--num_agents 15 \
--config agents_num_15 \
--agent_type generative_agent \
--max_seconds 32400 \
--save_per_seconds 5
