python ControlledFinals/InfluenceBattle.py --head_less \
--multi_process \
--skip_avatar_animation \
--output_dir output/CF/IB \
--challenge influence_battle \
--scene DETROIT \
--outdoor_objects_max_num 2 \
--resolution 512 \
--num_agents 15 \
--config agents_num_15 \
--agent_type generative_agent \
--max_seconds 21600 \
--save_per_seconds 10